### ISSUE TITLE
Great module!

### ISSUE THREAD

**Issue by srmnitc** [andersle/pytrr#4]
Hi @andersle ! Thanks for the great module. I find it really useful in handling trr files. I would like to use it as part of my module [pyscal](https://github.com/srmnitc/pyscal) which is used to calculate local atomic environment. I am thinking of extending it in the direction of Gromacs files. There are, however two issues, which I wanted to discuss with you-

- Ideally, it would be great if the code is under the BSD license instead of GNU GPL. pyscal is used within a larger project, and hence the license issue.

- Also, a conda recipe to have the package on conda-forge

Depending on your opinion there are two possibilities:

- I can adapt the pytrr code to the [pyscal trajectory](https://github.com/srmnitc/pyscal/blob/master/src/pyscal/traj_process.py) module, and list you as once of the contributers.

- If you feel its okay to release under a BSD license, I could then try to create a conda recipe and add it to conda-forge.

Once again, thanks for the great module! please let me know your opinion on the above.

**Comment by andersle** [comment]
Hi @srmnitc Thank you for the feedback! Here, I would prefer to keep the current license but I'm happy with you adapting the code to your module. There are probably some changes that could be done to make it a better fit with your project (on the top of my head I think I currently have some print statements here and there that could be removed). So I'm in favor of the option

> I can adapt the pytrr code to the pyscal trajectory module, and list you as once of the contributers.

As a side note, have you considered using [mdtraj](https://github.com/mdtraj/mdtraj)? It can handle a lot more file formats, in particular also ``xtc`` for GROMACS, and it also comes with a mini-language for selecting atoms, residues, waters, etc. from a topology. (mdtraj should already be a conda-installable.)

**Comment by srmnitc** [comment]
@andersle thanks for the reply! Yes, I have already provided support to use mdtraj. Often, I just need the atomic positions, and for that purpose I find pytrr to be lightweight and direct. Thanks once again, I will then go ahead and adapt the code.
